Don't inherit from MutableMapping
Since Flask 1.0 SessionMixin inherits from MutableMapping and we get:

TypeError: Cannot create a consistent method resolution
order (MRO) for bases MutableMapping, SessionMixin